// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "MapXML.hpp"

namespace mxml
{
  // MapXML
  // 

  const MapXML::room_sequence& MapXML::
  room () const
  {
    return this->room_;
  }

  MapXML::room_sequence& MapXML::
  room ()
  {
    return this->room_;
  }

  void MapXML::
  room (const room_sequence& s)
  {
    this->room_ = s;
  }


  // room
  // 

  const room::north_optional& room::
  north () const
  {
    return this->north_;
  }

  room::north_optional& room::
  north ()
  {
    return this->north_;
  }

  void room::
  north (const north_type& x)
  {
    this->north_.set (x);
  }

  void room::
  north (const north_optional& x)
  {
    this->north_ = x;
  }

  void room::
  north (::std::auto_ptr< north_type > x)
  {
    this->north_.set (x);
  }

  const room::south_optional& room::
  south () const
  {
    return this->south_;
  }

  room::south_optional& room::
  south ()
  {
    return this->south_;
  }

  void room::
  south (const south_type& x)
  {
    this->south_.set (x);
  }

  void room::
  south (const south_optional& x)
  {
    this->south_ = x;
  }

  void room::
  south (::std::auto_ptr< south_type > x)
  {
    this->south_.set (x);
  }

  const room::east_optional& room::
  east () const
  {
    return this->east_;
  }

  room::east_optional& room::
  east ()
  {
    return this->east_;
  }

  void room::
  east (const east_type& x)
  {
    this->east_.set (x);
  }

  void room::
  east (const east_optional& x)
  {
    this->east_ = x;
  }

  void room::
  east (::std::auto_ptr< east_type > x)
  {
    this->east_.set (x);
  }

  const room::west_optional& room::
  west () const
  {
    return this->west_;
  }

  room::west_optional& room::
  west ()
  {
    return this->west_;
  }

  void room::
  west (const west_type& x)
  {
    this->west_.set (x);
  }

  void room::
  west (const west_optional& x)
  {
    this->west_ = x;
  }

  void room::
  west (::std::auto_ptr< west_type > x)
  {
    this->west_.set (x);
  }

  const room::north_east_optional& room::
  north_east () const
  {
    return this->north_east_;
  }

  room::north_east_optional& room::
  north_east ()
  {
    return this->north_east_;
  }

  void room::
  north_east (const north_east_type& x)
  {
    this->north_east_.set (x);
  }

  void room::
  north_east (const north_east_optional& x)
  {
    this->north_east_ = x;
  }

  void room::
  north_east (::std::auto_ptr< north_east_type > x)
  {
    this->north_east_.set (x);
  }

  const room::north_west_optional& room::
  north_west () const
  {
    return this->north_west_;
  }

  room::north_west_optional& room::
  north_west ()
  {
    return this->north_west_;
  }

  void room::
  north_west (const north_west_type& x)
  {
    this->north_west_.set (x);
  }

  void room::
  north_west (const north_west_optional& x)
  {
    this->north_west_ = x;
  }

  void room::
  north_west (::std::auto_ptr< north_west_type > x)
  {
    this->north_west_.set (x);
  }

  const room::south_east_optional& room::
  south_east () const
  {
    return this->south_east_;
  }

  room::south_east_optional& room::
  south_east ()
  {
    return this->south_east_;
  }

  void room::
  south_east (const south_east_type& x)
  {
    this->south_east_.set (x);
  }

  void room::
  south_east (const south_east_optional& x)
  {
    this->south_east_ = x;
  }

  void room::
  south_east (::std::auto_ptr< south_east_type > x)
  {
    this->south_east_.set (x);
  }

  const room::south_west_optional& room::
  south_west () const
  {
    return this->south_west_;
  }

  room::south_west_optional& room::
  south_west ()
  {
    return this->south_west_;
  }

  void room::
  south_west (const south_west_type& x)
  {
    this->south_west_.set (x);
  }

  void room::
  south_west (const south_west_optional& x)
  {
    this->south_west_ = x;
  }

  void room::
  south_west (::std::auto_ptr< south_west_type > x)
  {
    this->south_west_.set (x);
  }

  const room::east_north_optional& room::
  east_north () const
  {
    return this->east_north_;
  }

  room::east_north_optional& room::
  east_north ()
  {
    return this->east_north_;
  }

  void room::
  east_north (const east_north_type& x)
  {
    this->east_north_.set (x);
  }

  void room::
  east_north (const east_north_optional& x)
  {
    this->east_north_ = x;
  }

  void room::
  east_north (::std::auto_ptr< east_north_type > x)
  {
    this->east_north_.set (x);
  }

  const room::east_south_optional& room::
  east_south () const
  {
    return this->east_south_;
  }

  room::east_south_optional& room::
  east_south ()
  {
    return this->east_south_;
  }

  void room::
  east_south (const east_south_type& x)
  {
    this->east_south_.set (x);
  }

  void room::
  east_south (const east_south_optional& x)
  {
    this->east_south_ = x;
  }

  void room::
  east_south (::std::auto_ptr< east_south_type > x)
  {
    this->east_south_.set (x);
  }

  const room::west_north_optional& room::
  west_north () const
  {
    return this->west_north_;
  }

  room::west_north_optional& room::
  west_north ()
  {
    return this->west_north_;
  }

  void room::
  west_north (const west_north_type& x)
  {
    this->west_north_.set (x);
  }

  void room::
  west_north (const west_north_optional& x)
  {
    this->west_north_ = x;
  }

  void room::
  west_north (::std::auto_ptr< west_north_type > x)
  {
    this->west_north_.set (x);
  }

  const room::west_south_optional& room::
  west_south () const
  {
    return this->west_south_;
  }

  room::west_south_optional& room::
  west_south ()
  {
    return this->west_south_;
  }

  void room::
  west_south (const west_south_type& x)
  {
    this->west_south_.set (x);
  }

  void room::
  west_south (const west_south_optional& x)
  {
    this->west_south_ = x;
  }

  void room::
  west_south (::std::auto_ptr< west_south_type > x)
  {
    this->west_south_.set (x);
  }

  const room::floor_optional& room::
  floor () const
  {
    return this->floor_;
  }

  room::floor_optional& room::
  floor ()
  {
    return this->floor_;
  }

  void room::
  floor (const floor_type& x)
  {
    this->floor_.set (x);
  }

  void room::
  floor (const floor_optional& x)
  {
    this->floor_ = x;
  }

  void room::
  floor (::std::auto_ptr< floor_type > x)
  {
    this->floor_.set (x);
  }

  const room::roof_optional& room::
  roof () const
  {
    return this->roof_;
  }

  room::roof_optional& room::
  roof ()
  {
    return this->roof_;
  }

  void room::
  roof (const roof_type& x)
  {
    this->roof_.set (x);
  }

  void room::
  roof (const roof_optional& x)
  {
    this->roof_ = x;
  }

  void room::
  roof (::std::auto_ptr< roof_type > x)
  {
    this->roof_.set (x);
  }

  const room::teleport_optional& room::
  teleport () const
  {
    return this->teleport_;
  }

  room::teleport_optional& room::
  teleport ()
  {
    return this->teleport_;
  }

  void room::
  teleport (const teleport_type& x)
  {
    this->teleport_.set (x);
  }

  void room::
  teleport (const teleport_optional& x)
  {
    this->teleport_ = x;
  }

  void room::
  teleport (::std::auto_ptr< teleport_type > x)
  {
    this->teleport_.set (x);
  }

  const room::teleport2_optional& room::
  teleport2 () const
  {
    return this->teleport2_;
  }

  room::teleport2_optional& room::
  teleport2 ()
  {
    return this->teleport2_;
  }

  void room::
  teleport2 (const teleport2_type& x)
  {
    this->teleport2_.set (x);
  }

  void room::
  teleport2 (const teleport2_optional& x)
  {
    this->teleport2_ = x;
  }

  void room::
  teleport2 (::std::auto_ptr< teleport2_type > x)
  {
    this->teleport2_.set (x);
  }

  const room::file_type& room::
  file () const
  {
    return this->file_.get ();
  }

  room::file_type& room::
  file ()
  {
    return this->file_.get ();
  }

  void room::
  file (const file_type& x)
  {
    this->file_.set (x);
  }

  void room::
  file (::std::auto_ptr< file_type > x)
  {
    this->file_.set (x);
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace mxml
{
  // MapXML
  //

  MapXML::
  MapXML ()
  : ::xml_schema::type (),
    room_ (this)
  {
  }

  MapXML::
  MapXML (const MapXML& x,
          ::xml_schema::flags f,
          ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    room_ (x.room_, f, this)
  {
  }

  MapXML::
  MapXML (const ::xercesc::DOMElement& e,
          ::xml_schema::flags f,
          ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    room_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
      this->parse (p, f);
    }
  }

  void MapXML::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // room
      //
      if (n.name () == "room" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< room_type > r (
          room_traits::create (i, f, this));

        this->room_.push_back (r);
        continue;
      }

      break;
    }
  }

  MapXML* MapXML::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class MapXML (*this, f, c);
  }

  MapXML& MapXML::
  operator= (const MapXML& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->room_ = x.room_;
    }

    return *this;
  }

  MapXML::
  ~MapXML ()
  {
  }

  // room
  //

  room::
  room (const file_type& file)
  : ::xml_schema::type (),
    north_ (this),
    south_ (this),
    east_ (this),
    west_ (this),
    north_east_ (this),
    north_west_ (this),
    south_east_ (this),
    south_west_ (this),
    east_north_ (this),
    east_south_ (this),
    west_north_ (this),
    west_south_ (this),
    floor_ (this),
    roof_ (this),
    teleport_ (this),
    teleport2_ (this),
    file_ (file, this)
  {
  }

  room::
  room (const room& x,
        ::xml_schema::flags f,
        ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    north_ (x.north_, f, this),
    south_ (x.south_, f, this),
    east_ (x.east_, f, this),
    west_ (x.west_, f, this),
    north_east_ (x.north_east_, f, this),
    north_west_ (x.north_west_, f, this),
    south_east_ (x.south_east_, f, this),
    south_west_ (x.south_west_, f, this),
    east_north_ (x.east_north_, f, this),
    east_south_ (x.east_south_, f, this),
    west_north_ (x.west_north_, f, this),
    west_south_ (x.west_south_, f, this),
    floor_ (x.floor_, f, this),
    roof_ (x.roof_, f, this),
    teleport_ (x.teleport_, f, this),
    teleport2_ (x.teleport2_, f, this),
    file_ (x.file_, f, this)
  {
  }

  room::
  room (const ::xercesc::DOMElement& e,
        ::xml_schema::flags f,
        ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    north_ (this),
    south_ (this),
    east_ (this),
    west_ (this),
    north_east_ (this),
    north_west_ (this),
    south_east_ (this),
    south_west_ (this),
    east_north_ (this),
    east_south_ (this),
    west_north_ (this),
    west_south_ (this),
    floor_ (this),
    roof_ (this),
    teleport_ (this),
    teleport2_ (this),
    file_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
      this->parse (p, f);
    }
  }

  void room::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // north
      //
      if (n.name () == "north" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< north_type > r (
          north_traits::create (i, f, this));

        if (!this->north_)
        {
          this->north_.set (r);
          continue;
        }
      }

      // south
      //
      if (n.name () == "south" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< south_type > r (
          south_traits::create (i, f, this));

        if (!this->south_)
        {
          this->south_.set (r);
          continue;
        }
      }

      // east
      //
      if (n.name () == "east" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< east_type > r (
          east_traits::create (i, f, this));

        if (!this->east_)
        {
          this->east_.set (r);
          continue;
        }
      }

      // west
      //
      if (n.name () == "west" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< west_type > r (
          west_traits::create (i, f, this));

        if (!this->west_)
        {
          this->west_.set (r);
          continue;
        }
      }

      // north-east
      //
      if (n.name () == "north-east" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< north_east_type > r (
          north_east_traits::create (i, f, this));

        if (!this->north_east_)
        {
          this->north_east_.set (r);
          continue;
        }
      }

      // north-west
      //
      if (n.name () == "north-west" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< north_west_type > r (
          north_west_traits::create (i, f, this));

        if (!this->north_west_)
        {
          this->north_west_.set (r);
          continue;
        }
      }

      // south-east
      //
      if (n.name () == "south-east" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< south_east_type > r (
          south_east_traits::create (i, f, this));

        if (!this->south_east_)
        {
          this->south_east_.set (r);
          continue;
        }
      }

      // south-west
      //
      if (n.name () == "south-west" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< south_west_type > r (
          south_west_traits::create (i, f, this));

        if (!this->south_west_)
        {
          this->south_west_.set (r);
          continue;
        }
      }

      // east-north
      //
      if (n.name () == "east-north" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< east_north_type > r (
          east_north_traits::create (i, f, this));

        if (!this->east_north_)
        {
          this->east_north_.set (r);
          continue;
        }
      }

      // east-south
      //
      if (n.name () == "east-south" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< east_south_type > r (
          east_south_traits::create (i, f, this));

        if (!this->east_south_)
        {
          this->east_south_.set (r);
          continue;
        }
      }

      // west-north
      //
      if (n.name () == "west-north" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< west_north_type > r (
          west_north_traits::create (i, f, this));

        if (!this->west_north_)
        {
          this->west_north_.set (r);
          continue;
        }
      }

      // west-south
      //
      if (n.name () == "west-south" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< west_south_type > r (
          west_south_traits::create (i, f, this));

        if (!this->west_south_)
        {
          this->west_south_.set (r);
          continue;
        }
      }

      // floor
      //
      if (n.name () == "floor" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< floor_type > r (
          floor_traits::create (i, f, this));

        if (!this->floor_)
        {
          this->floor_.set (r);
          continue;
        }
      }

      // roof
      //
      if (n.name () == "roof" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< roof_type > r (
          roof_traits::create (i, f, this));

        if (!this->roof_)
        {
          this->roof_.set (r);
          continue;
        }
      }

      // teleport
      //
      if (n.name () == "teleport" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< teleport_type > r (
          teleport_traits::create (i, f, this));

        if (!this->teleport_)
        {
          this->teleport_.set (r);
          continue;
        }
      }

      // teleport2
      //
      if (n.name () == "teleport2" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< teleport2_type > r (
          teleport2_traits::create (i, f, this));

        if (!this->teleport2_)
        {
          this->teleport2_.set (r);
          continue;
        }
      }

      break;
    }

    while (p.more_attributes ())
    {
      const ::xercesc::DOMAttr& i (p.next_attribute ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      if (n.name () == "file" && n.namespace_ ().empty ())
      {
        this->file_.set (file_traits::create (i, f, this));
        continue;
      }
    }

    if (!file_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< char > (
        "file",
        "");
    }
  }

  room* room::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class room (*this, f, c);
  }

  room& room::
  operator= (const room& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->north_ = x.north_;
      this->south_ = x.south_;
      this->east_ = x.east_;
      this->west_ = x.west_;
      this->north_east_ = x.north_east_;
      this->north_west_ = x.north_west_;
      this->south_east_ = x.south_east_;
      this->south_west_ = x.south_west_;
      this->east_north_ = x.east_north_;
      this->east_south_ = x.east_south_;
      this->west_north_ = x.west_north_;
      this->west_south_ = x.west_south_;
      this->floor_ = x.floor_;
      this->roof_ = x.roof_;
      this->teleport_ = x.teleport_;
      this->teleport2_ = x.teleport2_;
      this->file_ = x.file_;
    }

    return *this;
  }

  room::
  ~room ()
  {
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace mxml
{
  ::std::auto_ptr< ::mxml::MapXML >
  map (const ::std::string& u,
       ::xml_schema::flags f,
       const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::tree::error_handler< char > h;

    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        u, h, p, f));

    h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

    return ::std::auto_ptr< ::mxml::MapXML > (
      ::mxml::map (
        d, f | ::xml_schema::flags::own_dom, p));
  }

  ::std::auto_ptr< ::mxml::MapXML >
  map (const ::std::string& u,
       ::xml_schema::error_handler& h,
       ::xml_schema::flags f,
       const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        u, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    return ::std::auto_ptr< ::mxml::MapXML > (
      ::mxml::map (
        d, f | ::xml_schema::flags::own_dom, p));
  }

  ::std::auto_ptr< ::mxml::MapXML >
  map (const ::std::string& u,
       ::xercesc::DOMErrorHandler& h,
       ::xml_schema::flags f,
       const ::xml_schema::properties& p)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        u, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    return ::std::auto_ptr< ::mxml::MapXML > (
      ::mxml::map (
        d, f | ::xml_schema::flags::own_dom, p));
  }

  ::std::auto_ptr< ::mxml::MapXML >
  map (::std::istream& is,
       ::xml_schema::flags f,
       const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    return ::mxml::map (isrc, f, p);
  }

  ::std::auto_ptr< ::mxml::MapXML >
  map (::std::istream& is,
       ::xml_schema::error_handler& h,
       ::xml_schema::flags f,
       const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    return ::mxml::map (isrc, h, f, p);
  }

  ::std::auto_ptr< ::mxml::MapXML >
  map (::std::istream& is,
       ::xercesc::DOMErrorHandler& h,
       ::xml_schema::flags f,
       const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    return ::mxml::map (isrc, h, f, p);
  }

  ::std::auto_ptr< ::mxml::MapXML >
  map (::std::istream& is,
       const ::std::string& sid,
       ::xml_schema::flags f,
       const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    return ::mxml::map (isrc, f, p);
  }

  ::std::auto_ptr< ::mxml::MapXML >
  map (::std::istream& is,
       const ::std::string& sid,
       ::xml_schema::error_handler& h,
       ::xml_schema::flags f,
       const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    return ::mxml::map (isrc, h, f, p);
  }

  ::std::auto_ptr< ::mxml::MapXML >
  map (::std::istream& is,
       const ::std::string& sid,
       ::xercesc::DOMErrorHandler& h,
       ::xml_schema::flags f,
       const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    return ::mxml::map (isrc, h, f, p);
  }

  ::std::auto_ptr< ::mxml::MapXML >
  map (::xercesc::InputSource& i,
       ::xml_schema::flags f,
       const ::xml_schema::properties& p)
  {
    ::xsd::cxx::tree::error_handler< char > h;

    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        i, h, p, f));

    h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

    return ::std::auto_ptr< ::mxml::MapXML > (
      ::mxml::map (
        d, f | ::xml_schema::flags::own_dom, p));
  }

  ::std::auto_ptr< ::mxml::MapXML >
  map (::xercesc::InputSource& i,
       ::xml_schema::error_handler& h,
       ::xml_schema::flags f,
       const ::xml_schema::properties& p)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        i, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    return ::std::auto_ptr< ::mxml::MapXML > (
      ::mxml::map (
        d, f | ::xml_schema::flags::own_dom, p));
  }

  ::std::auto_ptr< ::mxml::MapXML >
  map (::xercesc::InputSource& i,
       ::xercesc::DOMErrorHandler& h,
       ::xml_schema::flags f,
       const ::xml_schema::properties& p)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        i, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    return ::std::auto_ptr< ::mxml::MapXML > (
      ::mxml::map (
        d, f | ::xml_schema::flags::own_dom, p));
  }

  ::std::auto_ptr< ::mxml::MapXML >
  map (const ::xercesc::DOMDocument& doc,
       ::xml_schema::flags f,
       const ::xml_schema::properties& p)
  {
    if (f & ::xml_schema::flags::keep_dom)
    {
      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
        static_cast< ::xercesc::DOMDocument* > (doc.cloneNode (true)));

      return ::std::auto_ptr< ::mxml::MapXML > (
        ::mxml::map (
          d, f | ::xml_schema::flags::own_dom, p));
    }

    const ::xercesc::DOMElement& e (*doc.getDocumentElement ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (e));

    if (n.name () == "map" &&
        n.namespace_ () == "")
    {
      ::std::auto_ptr< ::mxml::MapXML > r (
        ::xsd::cxx::tree::traits< ::mxml::MapXML, char >::create (
          e, f, 0));
      return r;
    }

    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "map",
      "");
  }

  ::std::auto_ptr< ::mxml::MapXML >
  map (::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d,
       ::xml_schema::flags f,
       const ::xml_schema::properties&)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > c (
      ((f & ::xml_schema::flags::keep_dom) &&
       !(f & ::xml_schema::flags::own_dom))
      ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
      : 0);

    ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
    const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (e));

    if (f & ::xml_schema::flags::keep_dom)
      doc.setUserData (::xml_schema::dom::tree_node_key,
                       (c.get () ? &c : &d),
                       0);

    if (n.name () == "map" &&
        n.namespace_ () == "")
    {
      ::std::auto_ptr< ::mxml::MapXML > r (
        ::xsd::cxx::tree::traits< ::mxml::MapXML, char >::create (
          e, f, 0));
      return r;
    }

    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "map",
      "");
  }
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

namespace mxml
{
  void
  map (::std::ostream& o,
       const ::mxml::MapXML& s,
       const ::xml_schema::namespace_infomap& m,
       const ::std::string& e,
       ::xml_schema::flags f)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0);

    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::mxml::map (s, m, f));

    ::xsd::cxx::tree::error_handler< char > h;

    ::xsd::cxx::xml::dom::ostream_format_target t (o);
    if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
    {
      h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
    }
  }

  void
  map (::std::ostream& o,
       const ::mxml::MapXML& s,
       ::xml_schema::error_handler& h,
       const ::xml_schema::namespace_infomap& m,
       const ::std::string& e,
       ::xml_schema::flags f)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0);

    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::mxml::map (s, m, f));
    ::xsd::cxx::xml::dom::ostream_format_target t (o);
    if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
    {
      throw ::xsd::cxx::tree::serialization< char > ();
    }
  }

  void
  map (::std::ostream& o,
       const ::mxml::MapXML& s,
       ::xercesc::DOMErrorHandler& h,
       const ::xml_schema::namespace_infomap& m,
       const ::std::string& e,
       ::xml_schema::flags f)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::mxml::map (s, m, f));
    ::xsd::cxx::xml::dom::ostream_format_target t (o);
    if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
    {
      throw ::xsd::cxx::tree::serialization< char > ();
    }
  }

  void
  map (::xercesc::XMLFormatTarget& t,
       const ::mxml::MapXML& s,
       const ::xml_schema::namespace_infomap& m,
       const ::std::string& e,
       ::xml_schema::flags f)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::mxml::map (s, m, f));

    ::xsd::cxx::tree::error_handler< char > h;

    if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
    {
      h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
    }
  }

  void
  map (::xercesc::XMLFormatTarget& t,
       const ::mxml::MapXML& s,
       ::xml_schema::error_handler& h,
       const ::xml_schema::namespace_infomap& m,
       const ::std::string& e,
       ::xml_schema::flags f)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::mxml::map (s, m, f));
    if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
    {
      throw ::xsd::cxx::tree::serialization< char > ();
    }
  }

  void
  map (::xercesc::XMLFormatTarget& t,
       const ::mxml::MapXML& s,
       ::xercesc::DOMErrorHandler& h,
       const ::xml_schema::namespace_infomap& m,
       const ::std::string& e,
       ::xml_schema::flags f)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::mxml::map (s, m, f));
    if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
    {
      throw ::xsd::cxx::tree::serialization< char > ();
    }
  }

  void
  map (::xercesc::DOMDocument& d,
       const ::mxml::MapXML& s,
       ::xml_schema::flags)
  {
    ::xercesc::DOMElement& e (*d.getDocumentElement ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (e));

    if (n.name () == "map" &&
        n.namespace_ () == "")
    {
      e << s;
    }
    else
    {
      throw ::xsd::cxx::tree::unexpected_element < char > (
        n.name (),
        n.namespace_ (),
        "map",
        "");
    }
  }

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument >
  map (const ::mxml::MapXML& s,
       const ::xml_schema::namespace_infomap& m,
       ::xml_schema::flags f)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::serialize< char > (
        "map",
        "",
        m, f));

    ::mxml::map (*d, s, f);
    return d;
  }

  void
  operator<< (::xercesc::DOMElement& e, const MapXML& i)
  {
    e << static_cast< const ::xml_schema::type& > (i);

    // room
    //
    for (MapXML::room_const_iterator
         b (i.room ().begin ()), n (i.room ().end ());
         b != n; ++b)
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "room",
          e));

      s << *b;
    }
  }

  void
  operator<< (::xercesc::DOMElement& e, const room& i)
  {
    e << static_cast< const ::xml_schema::type& > (i);

    // north
    //
    if (i.north ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "north",
          e));

      s << *i.north ();
    }

    // south
    //
    if (i.south ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "south",
          e));

      s << *i.south ();
    }

    // east
    //
    if (i.east ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "east",
          e));

      s << *i.east ();
    }

    // west
    //
    if (i.west ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "west",
          e));

      s << *i.west ();
    }

    // north-east
    //
    if (i.north_east ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "north-east",
          e));

      s << *i.north_east ();
    }

    // north-west
    //
    if (i.north_west ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "north-west",
          e));

      s << *i.north_west ();
    }

    // south-east
    //
    if (i.south_east ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "south-east",
          e));

      s << *i.south_east ();
    }

    // south-west
    //
    if (i.south_west ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "south-west",
          e));

      s << *i.south_west ();
    }

    // east-north
    //
    if (i.east_north ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "east-north",
          e));

      s << *i.east_north ();
    }

    // east-south
    //
    if (i.east_south ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "east-south",
          e));

      s << *i.east_south ();
    }

    // west-north
    //
    if (i.west_north ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "west-north",
          e));

      s << *i.west_north ();
    }

    // west-south
    //
    if (i.west_south ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "west-south",
          e));

      s << *i.west_south ();
    }

    // floor
    //
    if (i.floor ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "floor",
          e));

      s << *i.floor ();
    }

    // roof
    //
    if (i.roof ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "roof",
          e));

      s << *i.roof ();
    }

    // teleport
    //
    if (i.teleport ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "teleport",
          e));

      s << *i.teleport ();
    }

    // teleport2
    //
    if (i.teleport2 ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "teleport2",
          e));

      s << *i.teleport2 ();
    }

    // file
    //
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          "file",
          e));

      a << i.file ();
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

