// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "SaveGameXML.hpp"

namespace sgxml
{
  // SaveGameXML
  // 

  const SaveGameXML::exploredRooms_type& SaveGameXML::
  exploredRooms () const
  {
    return this->exploredRooms_.get ();
  }

  SaveGameXML::exploredRooms_type& SaveGameXML::
  exploredRooms ()
  {
    return this->exploredRooms_.get ();
  }

  void SaveGameXML::
  exploredRooms (const exploredRooms_type& x)
  {
    this->exploredRooms_.set (x);
  }

  void SaveGameXML::
  exploredRooms (::std::auto_ptr< exploredRooms_type > x)
  {
    this->exploredRooms_.set (x);
  }

  const SaveGameXML::freeByblos_type& SaveGameXML::
  freeByblos () const
  {
    return this->freeByblos_.get ();
  }

  SaveGameXML::freeByblos_type& SaveGameXML::
  freeByblos ()
  {
    return this->freeByblos_.get ();
  }

  void SaveGameXML::
  freeByblos (const freeByblos_type& x)
  {
    this->freeByblos_.set (x);
  }

  const SaveGameXML::freeEgyptus_type& SaveGameXML::
  freeEgyptus () const
  {
    return this->freeEgyptus_.get ();
  }

  SaveGameXML::freeEgyptus_type& SaveGameXML::
  freeEgyptus ()
  {
    return this->freeEgyptus_.get ();
  }

  void SaveGameXML::
  freeEgyptus (const freeEgyptus_type& x)
  {
    this->freeEgyptus_.set (x);
  }

  const SaveGameXML::freePenitentiary_type& SaveGameXML::
  freePenitentiary () const
  {
    return this->freePenitentiary_.get ();
  }

  SaveGameXML::freePenitentiary_type& SaveGameXML::
  freePenitentiary ()
  {
    return this->freePenitentiary_.get ();
  }

  void SaveGameXML::
  freePenitentiary (const freePenitentiary_type& x)
  {
    this->freePenitentiary_.set (x);
  }

  const SaveGameXML::freeSafari_type& SaveGameXML::
  freeSafari () const
  {
    return this->freeSafari_.get ();
  }

  SaveGameXML::freeSafari_type& SaveGameXML::
  freeSafari ()
  {
    return this->freeSafari_.get ();
  }

  void SaveGameXML::
  freeSafari (const freeSafari_type& x)
  {
    this->freeSafari_.set (x);
  }

  const SaveGameXML::freeBlacktooth_type& SaveGameXML::
  freeBlacktooth () const
  {
    return this->freeBlacktooth_.get ();
  }

  SaveGameXML::freeBlacktooth_type& SaveGameXML::
  freeBlacktooth ()
  {
    return this->freeBlacktooth_.get ();
  }

  void SaveGameXML::
  freeBlacktooth (const freeBlacktooth_type& x)
  {
    this->freeBlacktooth_.set (x);
  }

  const SaveGameXML::bonus_type& SaveGameXML::
  bonus () const
  {
    return this->bonus_.get ();
  }

  SaveGameXML::bonus_type& SaveGameXML::
  bonus ()
  {
    return this->bonus_.get ();
  }

  void SaveGameXML::
  bonus (const bonus_type& x)
  {
    this->bonus_.set (x);
  }

  void SaveGameXML::
  bonus (::std::auto_ptr< bonus_type > x)
  {
    this->bonus_.set (x);
  }

  const SaveGameXML::players_type& SaveGameXML::
  players () const
  {
    return this->players_.get ();
  }

  SaveGameXML::players_type& SaveGameXML::
  players ()
  {
    return this->players_.get ();
  }

  void SaveGameXML::
  players (const players_type& x)
  {
    this->players_.set (x);
  }

  void SaveGameXML::
  players (::std::auto_ptr< players_type > x)
  {
    this->players_.set (x);
  }


  // exploredRooms
  // 

  const exploredRooms::visited_sequence& exploredRooms::
  visited () const
  {
    return this->visited_;
  }

  exploredRooms::visited_sequence& exploredRooms::
  visited ()
  {
    return this->visited_;
  }

  void exploredRooms::
  visited (const visited_sequence& s)
  {
    this->visited_ = s;
  }


  // bonus
  // 

  const bonus::room_sequence& bonus::
  room () const
  {
    return this->room_;
  }

  bonus::room_sequence& bonus::
  room ()
  {
    return this->room_;
  }

  void bonus::
  room (const room_sequence& s)
  {
    this->room_ = s;
  }


  // players
  // 

  const players::player_sequence& players::
  player () const
  {
    return this->player_;
  }

  players::player_sequence& players::
  player ()
  {
    return this->player_;
  }

  void players::
  player (const player_sequence& s)
  {
    this->player_ = s;
  }


  // visited
  // 

  const visited::filename_type& visited::
  filename () const
  {
    return this->filename_.get ();
  }

  visited::filename_type& visited::
  filename ()
  {
    return this->filename_.get ();
  }

  void visited::
  filename (const filename_type& x)
  {
    this->filename_.set (x);
  }

  void visited::
  filename (::std::auto_ptr< filename_type > x)
  {
    this->filename_.set (x);
  }


  // room
  // 

  const room::label_type& room::
  label () const
  {
    return this->label_.get ();
  }

  room::label_type& room::
  label ()
  {
    return this->label_.get ();
  }

  void room::
  label (const label_type& x)
  {
    this->label_.set (x);
  }

  const room::filename_type& room::
  filename () const
  {
    return this->filename_.get ();
  }

  room::filename_type& room::
  filename ()
  {
    return this->filename_.get ();
  }

  void room::
  filename (const filename_type& x)
  {
    this->filename_.set (x);
  }

  void room::
  filename (::std::auto_ptr< filename_type > x)
  {
    this->filename_.set (x);
  }


  // player
  // 

  const player::active_type& player::
  active () const
  {
    return this->active_.get ();
  }

  player::active_type& player::
  active ()
  {
    return this->active_.get ();
  }

  void player::
  active (const active_type& x)
  {
    this->active_.set (x);
  }

  const player::roomFilename_type& player::
  roomFilename () const
  {
    return this->roomFilename_.get ();
  }

  player::roomFilename_type& player::
  roomFilename ()
  {
    return this->roomFilename_.get ();
  }

  void player::
  roomFilename (const roomFilename_type& x)
  {
    this->roomFilename_.set (x);
  }

  void player::
  roomFilename (::std::auto_ptr< roomFilename_type > x)
  {
    this->roomFilename_.set (x);
  }

  const player::x_type& player::
  x () const
  {
    return this->x_.get ();
  }

  player::x_type& player::
  x ()
  {
    return this->x_.get ();
  }

  void player::
  x (const x_type& x)
  {
    this->x_.set (x);
  }

  const player::y_type& player::
  y () const
  {
    return this->y_.get ();
  }

  player::y_type& player::
  y ()
  {
    return this->y_.get ();
  }

  void player::
  y (const y_type& x)
  {
    this->y_.set (x);
  }

  const player::z_type& player::
  z () const
  {
    return this->z_.get ();
  }

  player::z_type& player::
  z ()
  {
    return this->z_.get ();
  }

  void player::
  z (const z_type& x)
  {
    this->z_.set (x);
  }

  const player::direction_type& player::
  direction () const
  {
    return this->direction_.get ();
  }

  player::direction_type& player::
  direction ()
  {
    return this->direction_.get ();
  }

  void player::
  direction (const direction_type& x)
  {
    this->direction_.set (x);
  }

  const player::entry_type& player::
  entry () const
  {
    return this->entry_.get ();
  }

  player::entry_type& player::
  entry ()
  {
    return this->entry_.get ();
  }

  void player::
  entry (const entry_type& x)
  {
    this->entry_.set (x);
  }

  const player::lives_type& player::
  lives () const
  {
    return this->lives_.get ();
  }

  player::lives_type& player::
  lives ()
  {
    return this->lives_.get ();
  }

  void player::
  lives (const lives_type& x)
  {
    this->lives_.set (x);
  }

  const player::hasHorn_type& player::
  hasHorn () const
  {
    return this->hasHorn_.get ();
  }

  player::hasHorn_type& player::
  hasHorn ()
  {
    return this->hasHorn_.get ();
  }

  void player::
  hasHorn (const hasHorn_type& x)
  {
    this->hasHorn_.set (x);
  }

  const player::hasHandbag_type& player::
  hasHandbag () const
  {
    return this->hasHandbag_.get ();
  }

  player::hasHandbag_type& player::
  hasHandbag ()
  {
    return this->hasHandbag_.get ();
  }

  void player::
  hasHandbag (const hasHandbag_type& x)
  {
    this->hasHandbag_.set (x);
  }

  const player::ammo_type& player::
  ammo () const
  {
    return this->ammo_.get ();
  }

  player::ammo_type& player::
  ammo ()
  {
    return this->ammo_.get ();
  }

  void player::
  ammo (const ammo_type& x)
  {
    this->ammo_.set (x);
  }

  const player::label_type& player::
  label () const
  {
    return this->label_.get ();
  }

  player::label_type& player::
  label ()
  {
    return this->label_.get ();
  }

  void player::
  label (const label_type& x)
  {
    this->label_.set (x);
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace sgxml
{
  // SaveGameXML
  //

  SaveGameXML::
  SaveGameXML (const exploredRooms_type& exploredRooms,
               const freeByblos_type& freeByblos,
               const freeEgyptus_type& freeEgyptus,
               const freePenitentiary_type& freePenitentiary,
               const freeSafari_type& freeSafari,
               const freeBlacktooth_type& freeBlacktooth,
               const bonus_type& bonus,
               const players_type& players)
  : ::xml_schema::type (),
    exploredRooms_ (exploredRooms, this),
    freeByblos_ (freeByblos, this),
    freeEgyptus_ (freeEgyptus, this),
    freePenitentiary_ (freePenitentiary, this),
    freeSafari_ (freeSafari, this),
    freeBlacktooth_ (freeBlacktooth, this),
    bonus_ (bonus, this),
    players_ (players, this)
  {
  }

  SaveGameXML::
  SaveGameXML (::std::auto_ptr< exploredRooms_type > exploredRooms,
               const freeByblos_type& freeByblos,
               const freeEgyptus_type& freeEgyptus,
               const freePenitentiary_type& freePenitentiary,
               const freeSafari_type& freeSafari,
               const freeBlacktooth_type& freeBlacktooth,
               ::std::auto_ptr< bonus_type > bonus,
               ::std::auto_ptr< players_type > players)
  : ::xml_schema::type (),
    exploredRooms_ (exploredRooms, this),
    freeByblos_ (freeByblos, this),
    freeEgyptus_ (freeEgyptus, this),
    freePenitentiary_ (freePenitentiary, this),
    freeSafari_ (freeSafari, this),
    freeBlacktooth_ (freeBlacktooth, this),
    bonus_ (bonus, this),
    players_ (players, this)
  {
  }

  SaveGameXML::
  SaveGameXML (const SaveGameXML& x,
               ::xml_schema::flags f,
               ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    exploredRooms_ (x.exploredRooms_, f, this),
    freeByblos_ (x.freeByblos_, f, this),
    freeEgyptus_ (x.freeEgyptus_, f, this),
    freePenitentiary_ (x.freePenitentiary_, f, this),
    freeSafari_ (x.freeSafari_, f, this),
    freeBlacktooth_ (x.freeBlacktooth_, f, this),
    bonus_ (x.bonus_, f, this),
    players_ (x.players_, f, this)
  {
  }

  SaveGameXML::
  SaveGameXML (const ::xercesc::DOMElement& e,
               ::xml_schema::flags f,
               ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    exploredRooms_ (this),
    freeByblos_ (this),
    freeEgyptus_ (this),
    freePenitentiary_ (this),
    freeSafari_ (this),
    freeBlacktooth_ (this),
    bonus_ (this),
    players_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
      this->parse (p, f);
    }
  }

  void SaveGameXML::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // exploredRooms
      //
      if (n.name () == "exploredRooms" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< exploredRooms_type > r (
          exploredRooms_traits::create (i, f, this));

        if (!exploredRooms_.present ())
        {
          this->exploredRooms_.set (r);
          continue;
        }
      }

      // freeByblos
      //
      if (n.name () == "freeByblos" && n.namespace_ ().empty ())
      {
        if (!freeByblos_.present ())
        {
          this->freeByblos_.set (freeByblos_traits::create (i, f, this));
          continue;
        }
      }

      // freeEgyptus
      //
      if (n.name () == "freeEgyptus" && n.namespace_ ().empty ())
      {
        if (!freeEgyptus_.present ())
        {
          this->freeEgyptus_.set (freeEgyptus_traits::create (i, f, this));
          continue;
        }
      }

      // freePenitentiary
      //
      if (n.name () == "freePenitentiary" && n.namespace_ ().empty ())
      {
        if (!freePenitentiary_.present ())
        {
          this->freePenitentiary_.set (freePenitentiary_traits::create (i, f, this));
          continue;
        }
      }

      // freeSafari
      //
      if (n.name () == "freeSafari" && n.namespace_ ().empty ())
      {
        if (!freeSafari_.present ())
        {
          this->freeSafari_.set (freeSafari_traits::create (i, f, this));
          continue;
        }
      }

      // freeBlacktooth
      //
      if (n.name () == "freeBlacktooth" && n.namespace_ ().empty ())
      {
        if (!freeBlacktooth_.present ())
        {
          this->freeBlacktooth_.set (freeBlacktooth_traits::create (i, f, this));
          continue;
        }
      }

      // bonus
      //
      if (n.name () == "bonus" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< bonus_type > r (
          bonus_traits::create (i, f, this));

        if (!bonus_.present ())
        {
          this->bonus_.set (r);
          continue;
        }
      }

      // players
      //
      if (n.name () == "players" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< players_type > r (
          players_traits::create (i, f, this));

        if (!players_.present ())
        {
          this->players_.set (r);
          continue;
        }
      }

      break;
    }

    if (!exploredRooms_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "exploredRooms",
        "");
    }

    if (!freeByblos_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "freeByblos",
        "");
    }

    if (!freeEgyptus_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "freeEgyptus",
        "");
    }

    if (!freePenitentiary_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "freePenitentiary",
        "");
    }

    if (!freeSafari_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "freeSafari",
        "");
    }

    if (!freeBlacktooth_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "freeBlacktooth",
        "");
    }

    if (!bonus_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "bonus",
        "");
    }

    if (!players_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "players",
        "");
    }
  }

  SaveGameXML* SaveGameXML::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class SaveGameXML (*this, f, c);
  }

  SaveGameXML& SaveGameXML::
  operator= (const SaveGameXML& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->exploredRooms_ = x.exploredRooms_;
      this->freeByblos_ = x.freeByblos_;
      this->freeEgyptus_ = x.freeEgyptus_;
      this->freePenitentiary_ = x.freePenitentiary_;
      this->freeSafari_ = x.freeSafari_;
      this->freeBlacktooth_ = x.freeBlacktooth_;
      this->bonus_ = x.bonus_;
      this->players_ = x.players_;
    }

    return *this;
  }

  SaveGameXML::
  ~SaveGameXML ()
  {
  }

  // exploredRooms
  //

  exploredRooms::
  exploredRooms ()
  : ::xml_schema::type (),
    visited_ (this)
  {
  }

  exploredRooms::
  exploredRooms (const exploredRooms& x,
                 ::xml_schema::flags f,
                 ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    visited_ (x.visited_, f, this)
  {
  }

  exploredRooms::
  exploredRooms (const ::xercesc::DOMElement& e,
                 ::xml_schema::flags f,
                 ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    visited_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
      this->parse (p, f);
    }
  }

  void exploredRooms::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // visited
      //
      if (n.name () == "visited" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< visited_type > r (
          visited_traits::create (i, f, this));

        this->visited_.push_back (r);
        continue;
      }

      break;
    }
  }

  exploredRooms* exploredRooms::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class exploredRooms (*this, f, c);
  }

  exploredRooms& exploredRooms::
  operator= (const exploredRooms& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->visited_ = x.visited_;
    }

    return *this;
  }

  exploredRooms::
  ~exploredRooms ()
  {
  }

  // bonus
  //

  bonus::
  bonus ()
  : ::xml_schema::type (),
    room_ (this)
  {
  }

  bonus::
  bonus (const bonus& x,
         ::xml_schema::flags f,
         ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    room_ (x.room_, f, this)
  {
  }

  bonus::
  bonus (const ::xercesc::DOMElement& e,
         ::xml_schema::flags f,
         ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    room_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
      this->parse (p, f);
    }
  }

  void bonus::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // room
      //
      if (n.name () == "room" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< room_type > r (
          room_traits::create (i, f, this));

        this->room_.push_back (r);
        continue;
      }

      break;
    }
  }

  bonus* bonus::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class bonus (*this, f, c);
  }

  bonus& bonus::
  operator= (const bonus& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->room_ = x.room_;
    }

    return *this;
  }

  bonus::
  ~bonus ()
  {
  }

  // players
  //

  players::
  players ()
  : ::xml_schema::type (),
    player_ (this)
  {
  }

  players::
  players (const players& x,
           ::xml_schema::flags f,
           ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    player_ (x.player_, f, this)
  {
  }

  players::
  players (const ::xercesc::DOMElement& e,
           ::xml_schema::flags f,
           ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    player_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
      this->parse (p, f);
    }
  }

  void players::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // player
      //
      if (n.name () == "player" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< player_type > r (
          player_traits::create (i, f, this));

        this->player_.push_back (r);
        continue;
      }

      break;
    }
  }

  players* players::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class players (*this, f, c);
  }

  players& players::
  operator= (const players& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->player_ = x.player_;
    }

    return *this;
  }

  players::
  ~players ()
  {
  }

  // visited
  //

  visited::
  visited (const filename_type& filename)
  : ::xml_schema::type (),
    filename_ (filename, this)
  {
  }

  visited::
  visited (const visited& x,
           ::xml_schema::flags f,
           ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    filename_ (x.filename_, f, this)
  {
  }

  visited::
  visited (const ::xercesc::DOMElement& e,
           ::xml_schema::flags f,
           ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    filename_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, false, false, true);
      this->parse (p, f);
    }
  }

  void visited::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    while (p.more_attributes ())
    {
      const ::xercesc::DOMAttr& i (p.next_attribute ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      if (n.name () == "filename" && n.namespace_ ().empty ())
      {
        this->filename_.set (filename_traits::create (i, f, this));
        continue;
      }
    }

    if (!filename_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< char > (
        "filename",
        "");
    }
  }

  visited* visited::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class visited (*this, f, c);
  }

  visited& visited::
  operator= (const visited& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->filename_ = x.filename_;
    }

    return *this;
  }

  visited::
  ~visited ()
  {
  }

  // room
  //

  room::
  room (const label_type& label,
        const filename_type& filename)
  : ::xml_schema::type (),
    label_ (label, this),
    filename_ (filename, this)
  {
  }

  room::
  room (const room& x,
        ::xml_schema::flags f,
        ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    label_ (x.label_, f, this),
    filename_ (x.filename_, f, this)
  {
  }

  room::
  room (const ::xercesc::DOMElement& e,
        ::xml_schema::flags f,
        ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    label_ (this),
    filename_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
      this->parse (p, f);
    }
  }

  void room::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // label
      //
      if (n.name () == "label" && n.namespace_ ().empty ())
      {
        if (!label_.present ())
        {
          this->label_.set (label_traits::create (i, f, this));
          continue;
        }
      }

      break;
    }

    if (!label_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "label",
        "");
    }

    while (p.more_attributes ())
    {
      const ::xercesc::DOMAttr& i (p.next_attribute ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      if (n.name () == "filename" && n.namespace_ ().empty ())
      {
        this->filename_.set (filename_traits::create (i, f, this));
        continue;
      }
    }

    if (!filename_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< char > (
        "filename",
        "");
    }
  }

  room* room::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class room (*this, f, c);
  }

  room& room::
  operator= (const room& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->label_ = x.label_;
      this->filename_ = x.filename_;
    }

    return *this;
  }

  room::
  ~room ()
  {
  }

  // player
  //

  player::
  player (const active_type& active,
          const roomFilename_type& roomFilename,
          const x_type& x,
          const y_type& y,
          const z_type& z,
          const direction_type& direction,
          const entry_type& entry,
          const lives_type& lives,
          const hasHorn_type& hasHorn,
          const hasHandbag_type& hasHandbag,
          const ammo_type& ammo,
          const label_type& label)
  : ::xml_schema::type (),
    active_ (active, this),
    roomFilename_ (roomFilename, this),
    x_ (x, this),
    y_ (y, this),
    z_ (z, this),
    direction_ (direction, this),
    entry_ (entry, this),
    lives_ (lives, this),
    hasHorn_ (hasHorn, this),
    hasHandbag_ (hasHandbag, this),
    ammo_ (ammo, this),
    label_ (label, this)
  {
  }

  player::
  player (const player& x,
          ::xml_schema::flags f,
          ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    active_ (x.active_, f, this),
    roomFilename_ (x.roomFilename_, f, this),
    x_ (x.x_, f, this),
    y_ (x.y_, f, this),
    z_ (x.z_, f, this),
    direction_ (x.direction_, f, this),
    entry_ (x.entry_, f, this),
    lives_ (x.lives_, f, this),
    hasHorn_ (x.hasHorn_, f, this),
    hasHandbag_ (x.hasHandbag_, f, this),
    ammo_ (x.ammo_, f, this),
    label_ (x.label_, f, this)
  {
  }

  player::
  player (const ::xercesc::DOMElement& e,
          ::xml_schema::flags f,
          ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    active_ (this),
    roomFilename_ (this),
    x_ (this),
    y_ (this),
    z_ (this),
    direction_ (this),
    entry_ (this),
    lives_ (this),
    hasHorn_ (this),
    hasHandbag_ (this),
    ammo_ (this),
    label_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
      this->parse (p, f);
    }
  }

  void player::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // active
      //
      if (n.name () == "active" && n.namespace_ ().empty ())
      {
        if (!active_.present ())
        {
          this->active_.set (active_traits::create (i, f, this));
          continue;
        }
      }

      // roomFilename
      //
      if (n.name () == "roomFilename" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< roomFilename_type > r (
          roomFilename_traits::create (i, f, this));

        if (!roomFilename_.present ())
        {
          this->roomFilename_.set (r);
          continue;
        }
      }

      // x
      //
      if (n.name () == "x" && n.namespace_ ().empty ())
      {
        if (!x_.present ())
        {
          this->x_.set (x_traits::create (i, f, this));
          continue;
        }
      }

      // y
      //
      if (n.name () == "y" && n.namespace_ ().empty ())
      {
        if (!y_.present ())
        {
          this->y_.set (y_traits::create (i, f, this));
          continue;
        }
      }

      // z
      //
      if (n.name () == "z" && n.namespace_ ().empty ())
      {
        if (!z_.present ())
        {
          this->z_.set (z_traits::create (i, f, this));
          continue;
        }
      }

      // direction
      //
      if (n.name () == "direction" && n.namespace_ ().empty ())
      {
        if (!direction_.present ())
        {
          this->direction_.set (direction_traits::create (i, f, this));
          continue;
        }
      }

      // entry
      //
      if (n.name () == "entry" && n.namespace_ ().empty ())
      {
        if (!entry_.present ())
        {
          this->entry_.set (entry_traits::create (i, f, this));
          continue;
        }
      }

      // lives
      //
      if (n.name () == "lives" && n.namespace_ ().empty ())
      {
        if (!lives_.present ())
        {
          this->lives_.set (lives_traits::create (i, f, this));
          continue;
        }
      }

      // hasHorn
      //
      if (n.name () == "hasHorn" && n.namespace_ ().empty ())
      {
        if (!hasHorn_.present ())
        {
          this->hasHorn_.set (hasHorn_traits::create (i, f, this));
          continue;
        }
      }

      // hasHandbag
      //
      if (n.name () == "hasHandbag" && n.namespace_ ().empty ())
      {
        if (!hasHandbag_.present ())
        {
          this->hasHandbag_.set (hasHandbag_traits::create (i, f, this));
          continue;
        }
      }

      // ammo
      //
      if (n.name () == "ammo" && n.namespace_ ().empty ())
      {
        if (!ammo_.present ())
        {
          this->ammo_.set (ammo_traits::create (i, f, this));
          continue;
        }
      }

      break;
    }

    if (!active_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "active",
        "");
    }

    if (!roomFilename_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "roomFilename",
        "");
    }

    if (!x_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "x",
        "");
    }

    if (!y_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "y",
        "");
    }

    if (!z_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "z",
        "");
    }

    if (!direction_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "direction",
        "");
    }

    if (!entry_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "entry",
        "");
    }

    if (!lives_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "lives",
        "");
    }

    if (!hasHorn_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "hasHorn",
        "");
    }

    if (!hasHandbag_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "hasHandbag",
        "");
    }

    if (!ammo_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "ammo",
        "");
    }

    while (p.more_attributes ())
    {
      const ::xercesc::DOMAttr& i (p.next_attribute ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      if (n.name () == "label" && n.namespace_ ().empty ())
      {
        this->label_.set (label_traits::create (i, f, this));
        continue;
      }
    }

    if (!label_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< char > (
        "label",
        "");
    }
  }

  player* player::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class player (*this, f, c);
  }

  player& player::
  operator= (const player& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->active_ = x.active_;
      this->roomFilename_ = x.roomFilename_;
      this->x_ = x.x_;
      this->y_ = x.y_;
      this->z_ = x.z_;
      this->direction_ = x.direction_;
      this->entry_ = x.entry_;
      this->lives_ = x.lives_;
      this->hasHorn_ = x.hasHorn_;
      this->hasHandbag_ = x.hasHandbag_;
      this->ammo_ = x.ammo_;
      this->label_ = x.label_;
    }

    return *this;
  }

  player::
  ~player ()
  {
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace sgxml
{
  ::std::auto_ptr< ::sgxml::SaveGameXML >
  savegame (const ::std::string& u,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::tree::error_handler< char > h;

    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        u, h, p, f));

    h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

    return ::std::auto_ptr< ::sgxml::SaveGameXML > (
      ::sgxml::savegame (
        d, f | ::xml_schema::flags::own_dom, p));
  }

  ::std::auto_ptr< ::sgxml::SaveGameXML >
  savegame (const ::std::string& u,
            ::xml_schema::error_handler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        u, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    return ::std::auto_ptr< ::sgxml::SaveGameXML > (
      ::sgxml::savegame (
        d, f | ::xml_schema::flags::own_dom, p));
  }

  ::std::auto_ptr< ::sgxml::SaveGameXML >
  savegame (const ::std::string& u,
            ::xercesc::DOMErrorHandler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        u, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    return ::std::auto_ptr< ::sgxml::SaveGameXML > (
      ::sgxml::savegame (
        d, f | ::xml_schema::flags::own_dom, p));
  }

  ::std::auto_ptr< ::sgxml::SaveGameXML >
  savegame (::std::istream& is,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    return ::sgxml::savegame (isrc, f, p);
  }

  ::std::auto_ptr< ::sgxml::SaveGameXML >
  savegame (::std::istream& is,
            ::xml_schema::error_handler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    return ::sgxml::savegame (isrc, h, f, p);
  }

  ::std::auto_ptr< ::sgxml::SaveGameXML >
  savegame (::std::istream& is,
            ::xercesc::DOMErrorHandler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    return ::sgxml::savegame (isrc, h, f, p);
  }

  ::std::auto_ptr< ::sgxml::SaveGameXML >
  savegame (::std::istream& is,
            const ::std::string& sid,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    return ::sgxml::savegame (isrc, f, p);
  }

  ::std::auto_ptr< ::sgxml::SaveGameXML >
  savegame (::std::istream& is,
            const ::std::string& sid,
            ::xml_schema::error_handler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    return ::sgxml::savegame (isrc, h, f, p);
  }

  ::std::auto_ptr< ::sgxml::SaveGameXML >
  savegame (::std::istream& is,
            const ::std::string& sid,
            ::xercesc::DOMErrorHandler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    return ::sgxml::savegame (isrc, h, f, p);
  }

  ::std::auto_ptr< ::sgxml::SaveGameXML >
  savegame (::xercesc::InputSource& i,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
  {
    ::xsd::cxx::tree::error_handler< char > h;

    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        i, h, p, f));

    h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

    return ::std::auto_ptr< ::sgxml::SaveGameXML > (
      ::sgxml::savegame (
        d, f | ::xml_schema::flags::own_dom, p));
  }

  ::std::auto_ptr< ::sgxml::SaveGameXML >
  savegame (::xercesc::InputSource& i,
            ::xml_schema::error_handler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        i, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    return ::std::auto_ptr< ::sgxml::SaveGameXML > (
      ::sgxml::savegame (
        d, f | ::xml_schema::flags::own_dom, p));
  }

  ::std::auto_ptr< ::sgxml::SaveGameXML >
  savegame (::xercesc::InputSource& i,
            ::xercesc::DOMErrorHandler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        i, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    return ::std::auto_ptr< ::sgxml::SaveGameXML > (
      ::sgxml::savegame (
        d, f | ::xml_schema::flags::own_dom, p));
  }

  ::std::auto_ptr< ::sgxml::SaveGameXML >
  savegame (const ::xercesc::DOMDocument& doc,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
  {
    if (f & ::xml_schema::flags::keep_dom)
    {
      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
        static_cast< ::xercesc::DOMDocument* > (doc.cloneNode (true)));

      return ::std::auto_ptr< ::sgxml::SaveGameXML > (
        ::sgxml::savegame (
          d, f | ::xml_schema::flags::own_dom, p));
    }

    const ::xercesc::DOMElement& e (*doc.getDocumentElement ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (e));

    if (n.name () == "savegame" &&
        n.namespace_ () == "")
    {
      ::std::auto_ptr< ::sgxml::SaveGameXML > r (
        ::xsd::cxx::tree::traits< ::sgxml::SaveGameXML, char >::create (
          e, f, 0));
      return r;
    }

    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "savegame",
      "");
  }

  ::std::auto_ptr< ::sgxml::SaveGameXML >
  savegame (::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d,
            ::xml_schema::flags f,
            const ::xml_schema::properties&)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > c (
      ((f & ::xml_schema::flags::keep_dom) &&
       !(f & ::xml_schema::flags::own_dom))
      ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
      : 0);

    ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
    const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (e));

    if (f & ::xml_schema::flags::keep_dom)
      doc.setUserData (::xml_schema::dom::tree_node_key,
                       (c.get () ? &c : &d),
                       0);

    if (n.name () == "savegame" &&
        n.namespace_ () == "")
    {
      ::std::auto_ptr< ::sgxml::SaveGameXML > r (
        ::xsd::cxx::tree::traits< ::sgxml::SaveGameXML, char >::create (
          e, f, 0));
      return r;
    }

    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "savegame",
      "");
  }
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

namespace sgxml
{
  void
  savegame (::std::ostream& o,
            const ::sgxml::SaveGameXML& s,
            const ::xml_schema::namespace_infomap& m,
            const ::std::string& e,
            ::xml_schema::flags f)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0);

    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::sgxml::savegame (s, m, f));

    ::xsd::cxx::tree::error_handler< char > h;

    ::xsd::cxx::xml::dom::ostream_format_target t (o);
    if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
    {
      h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
    }
  }

  void
  savegame (::std::ostream& o,
            const ::sgxml::SaveGameXML& s,
            ::xml_schema::error_handler& h,
            const ::xml_schema::namespace_infomap& m,
            const ::std::string& e,
            ::xml_schema::flags f)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0);

    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::sgxml::savegame (s, m, f));
    ::xsd::cxx::xml::dom::ostream_format_target t (o);
    if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
    {
      throw ::xsd::cxx::tree::serialization< char > ();
    }
  }

  void
  savegame (::std::ostream& o,
            const ::sgxml::SaveGameXML& s,
            ::xercesc::DOMErrorHandler& h,
            const ::xml_schema::namespace_infomap& m,
            const ::std::string& e,
            ::xml_schema::flags f)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::sgxml::savegame (s, m, f));
    ::xsd::cxx::xml::dom::ostream_format_target t (o);
    if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
    {
      throw ::xsd::cxx::tree::serialization< char > ();
    }
  }

  void
  savegame (::xercesc::XMLFormatTarget& t,
            const ::sgxml::SaveGameXML& s,
            const ::xml_schema::namespace_infomap& m,
            const ::std::string& e,
            ::xml_schema::flags f)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::sgxml::savegame (s, m, f));

    ::xsd::cxx::tree::error_handler< char > h;

    if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
    {
      h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
    }
  }

  void
  savegame (::xercesc::XMLFormatTarget& t,
            const ::sgxml::SaveGameXML& s,
            ::xml_schema::error_handler& h,
            const ::xml_schema::namespace_infomap& m,
            const ::std::string& e,
            ::xml_schema::flags f)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::sgxml::savegame (s, m, f));
    if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
    {
      throw ::xsd::cxx::tree::serialization< char > ();
    }
  }

  void
  savegame (::xercesc::XMLFormatTarget& t,
            const ::sgxml::SaveGameXML& s,
            ::xercesc::DOMErrorHandler& h,
            const ::xml_schema::namespace_infomap& m,
            const ::std::string& e,
            ::xml_schema::flags f)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::sgxml::savegame (s, m, f));
    if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
    {
      throw ::xsd::cxx::tree::serialization< char > ();
    }
  }

  void
  savegame (::xercesc::DOMDocument& d,
            const ::sgxml::SaveGameXML& s,
            ::xml_schema::flags)
  {
    ::xercesc::DOMElement& e (*d.getDocumentElement ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (e));

    if (n.name () == "savegame" &&
        n.namespace_ () == "")
    {
      e << s;
    }
    else
    {
      throw ::xsd::cxx::tree::unexpected_element < char > (
        n.name (),
        n.namespace_ (),
        "savegame",
        "");
    }
  }

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument >
  savegame (const ::sgxml::SaveGameXML& s,
            const ::xml_schema::namespace_infomap& m,
            ::xml_schema::flags f)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::serialize< char > (
        "savegame",
        "",
        m, f));

    ::sgxml::savegame (*d, s, f);
    return d;
  }

  void
  operator<< (::xercesc::DOMElement& e, const SaveGameXML& i)
  {
    e << static_cast< const ::xml_schema::type& > (i);

    // exploredRooms
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "exploredRooms",
          e));

      s << i.exploredRooms ();
    }

    // freeByblos
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "freeByblos",
          e));

      s << i.freeByblos ();
    }

    // freeEgyptus
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "freeEgyptus",
          e));

      s << i.freeEgyptus ();
    }

    // freePenitentiary
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "freePenitentiary",
          e));

      s << i.freePenitentiary ();
    }

    // freeSafari
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "freeSafari",
          e));

      s << i.freeSafari ();
    }

    // freeBlacktooth
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "freeBlacktooth",
          e));

      s << i.freeBlacktooth ();
    }

    // bonus
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "bonus",
          e));

      s << i.bonus ();
    }

    // players
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "players",
          e));

      s << i.players ();
    }
  }

  void
  operator<< (::xercesc::DOMElement& e, const exploredRooms& i)
  {
    e << static_cast< const ::xml_schema::type& > (i);

    // visited
    //
    for (exploredRooms::visited_const_iterator
         b (i.visited ().begin ()), n (i.visited ().end ());
         b != n; ++b)
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "visited",
          e));

      s << *b;
    }
  }

  void
  operator<< (::xercesc::DOMElement& e, const bonus& i)
  {
    e << static_cast< const ::xml_schema::type& > (i);

    // room
    //
    for (bonus::room_const_iterator
         b (i.room ().begin ()), n (i.room ().end ());
         b != n; ++b)
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "room",
          e));

      s << *b;
    }
  }

  void
  operator<< (::xercesc::DOMElement& e, const players& i)
  {
    e << static_cast< const ::xml_schema::type& > (i);

    // player
    //
    for (players::player_const_iterator
         b (i.player ().begin ()), n (i.player ().end ());
         b != n; ++b)
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "player",
          e));

      s << *b;
    }
  }

  void
  operator<< (::xercesc::DOMElement& e, const visited& i)
  {
    e << static_cast< const ::xml_schema::type& > (i);

    // filename
    //
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          "filename",
          e));

      a << i.filename ();
    }
  }

  void
  operator<< (::xercesc::DOMElement& e, const room& i)
  {
    e << static_cast< const ::xml_schema::type& > (i);

    // label
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "label",
          e));

      s << i.label ();
    }

    // filename
    //
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          "filename",
          e));

      a << i.filename ();
    }
  }

  void
  operator<< (::xercesc::DOMElement& e, const player& i)
  {
    e << static_cast< const ::xml_schema::type& > (i);

    // active
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "active",
          e));

      s << i.active ();
    }

    // roomFilename
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "roomFilename",
          e));

      s << i.roomFilename ();
    }

    // x
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "x",
          e));

      s << i.x ();
    }

    // y
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "y",
          e));

      s << i.y ();
    }

    // z
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "z",
          e));

      s << i.z ();
    }

    // direction
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "direction",
          e));

      s << i.direction ();
    }

    // entry
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "entry",
          e));

      s << i.entry ();
    }

    // lives
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "lives",
          e));

      s << i.lives ();
    }

    // hasHorn
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "hasHorn",
          e));

      s << i.hasHorn ();
    }

    // hasHandbag
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "hasHandbag",
          e));

      s << i.hasHandbag ();
    }

    // ammo
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "ammo",
          e));

      s << i.ammo ();
    }

    // label
    //
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          "label",
          e));

      a << i.label ();
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

